/*
 * Copyright (c) 2014-2016 GMRV/URJC.
 *
 * Authors: Sergio Galindo <sergio.galindo@urjc.es>
 *
 * This file is part of PReFr <https://gmrv.gitlab.com/nsviz/prefr>
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License version 3.0 as published
 * by the Free Software Foundation.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE.  See the GNU Lesser General Public License for more
 * details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with this library; if not, write to the Free Software Foundation, Inc.,
 * 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
 *
 */
#ifndef __PREFR__SOURCE__
#define __PREFR__SOURCE__

#include <prefr/api.h>

#include "../utils/types.h"

#include "Particles.h"
#include "Cluster.h"
#include "Sampler.h"

#include "../utils/Timer.hpp"

namespace prefr
{

  class Cluster;
  class Sampler;

  class SampledValues
  {
  public:

    glm::vec3 position;
    glm::vec3 direction;
    glm::mat4 rotation;
  };

  /*! \class Source
   *
   * \brief This class provides the base for the emission of particles for
   * a Cluster object.
   *
   * This class provides the base for the emission of particles for
   * a Cluster object. The Cluster object uses a Source object for handling
   * the emission according to the emission rate with the position, direction
   * and rotation generated by the given Sampler. Emission can be set to
   * be repeated indefinitely or to a certain number of cycles.
   *
   * Note: Reimplement this class to create a different behavior.
   *
   */
  class Source
  {
    friend class ParticleSystem;
    friend class Cluster;
    friend class Updater;

  public:

    PREFR_API
    Source( float emissionRate,
            const glm::vec3& position,
            Sampler* sampler = nullptr );

    PREFR_API
    virtual ~Source( void );

    PREFR_API virtual bool Active( );
    PREFR_API virtual bool Emits( ) const;
    PREFR_API virtual bool Continue( ) const;
    PREFR_API virtual bool Finished( );
    PREFR_API virtual void Restart( );

    PREFR_API virtual const int& GetBudget( );
    PREFR_API virtual void PrepareFrame( const float& deltaTime );
    PREFR_API virtual void CloseFrame( );

    PREFR_API virtual void IncreaseAlive( );
    PREFR_API virtual void CheckEmissionEnd( );

    PREFR_API virtual void ReduceBudgetBy( const unsigned int& decrement = 1 );

    PREFR_API virtual void maxEmissionCycles( unsigned int cycles );

    PREFR_API Cluster* cluster( void );
    PREFR_API void cluster( Cluster* cluster_ );

    PREFR_API void sampler( Sampler* sampler );
    PREFR_API const Sampler* sampler( void ) const;

    PREFR_API glm::vec3 position( void ) const;
    PREFR_API void sample( SampledValues* ) const;

    PREFR_API std::vector< unsigned int >& deadParticles( void );
    PREFR_API std::vector< unsigned int >& particlesToEmit( void );

  protected:

    virtual void InitializeParticles( void );
    virtual void PrepareParticles( void );

    Cluster* _cluster;

    Sampler* _sampler;

    glm::vec3 _position;

    std::vector< unsigned int > _deadParticles;
    std::vector< unsigned int > _particlesToEmit;

    float _emissionRate;
    unsigned int _totalParticles;

    float _emissionAcc;
    int _particlesBudget;
    bool _active;
    bool _continueEmission;
    bool _finished;

    bool _autoDeactivateWhenFinished;

    bool _killParticlesIfInactive;

    int _lastFrameAliveParticles;

    unsigned int _emittedParticles;
    unsigned int _maxEmissionCycles;
    unsigned int _currentCycle;

  };

  typedef std::vector< Source* > SourcesArray;

  /*! \class TimedSource
   *
   * \brief This class provides the feature of emitting within a time frame.
   *
   * This class adds the base Source the feature of establishing a
   * time frame in which particles will be emitted. This time window will be
   * restarted after finishing, allowing to emit repeatedly according to the
   * set period.
   *
   * @see utils::SingleFrameTimer
   * @see Source
   *
   */
  class TimedSource : public Source, public utils::SingleFrameTimer
  {
  public:

    PREFR_API TimedSource( float emissionRate_, glm::vec3 position_ );
    PREFR_API TimedSource( float emissionRate_, glm::vec3 position_,
                           float period, float offset, float duration );

    PREFR_API virtual bool Emits( ) const;

    PREFR_API virtual void CheckEmissionEnd( );

    PREFR_API virtual void PrepareFrame( const float& deltaTime );
    PREFR_API virtual void CloseFrame( );

  };

}


#endif /* __PREFR__SOURCE__ */
